### ISSUE TITLE
Expression support

### ISSUE THREAD

**Issue by Aiosa** [lingarajsankaravelu/Katex#10]
Hi,

At first - nice work, I really like your mathview.
However, I would like to know which expressions does it support. I tried several examples from [katex](https://khan.github.io/KaTeX/function-support.html) and nearly one third was invalid. 
Some, such as Delimiters worked fine, but Accents were one big error. Especially over-, under- expressions.

Is it a bug or it just supports only a part of KaTeX?
Thanks

**Comment by lingarajsankaravelu** [comment]
@Aiosa I am extremely sorry for replying to your question after a long time. i am sure you might have figured out answer for this on your own, anyways  By Default this mathview should support all things katex.org can render. if you still have any problem. you can use the code from modification branch. It has katex.org recent changes and  thanks for all your answers in the issues section. 👍
