### ISSUE TITLE
Not showing proper latex statements 

### ISSUE THREAD

**Issue by navdeepwebdeskers** [lingarajsankaravelu/Katex#13]
KaTeX auto-render: Failed to parse `x=\\frac{1+y}{1+2z^2}` with ", source: file:///android_asset/katex/contrib/auto-render.min.js

**Comment by Aiosa** [comment]
Hard to say without any context at all.. the formula itself seems to be ok (if you are using \\\\ to escape backslash)

Try one of the following:
Make sure you enclosed the formula within dolar symbols
Try to replace frac with dfrac
Provide us with more information, eg usage

**Comment by navdeepwebdeskers** [comment]
Its working Dude!
only i have to enclose with the dolar symbols

**Comment by Aiosa** [comment]
Next time please, read the README first - get familiar with the right use.

MathView is nothing else than modified webView, as Katex is meant to be used for web page contents, thuss webView is only a simple small hack to bring math formulas to mobile phones. 

This means your input can include HTML and CSS as well (not within the dollar symbols though)
