### ISSUE TITLE
Text Aligment in View

### ISSUE THREAD

**Issue by edward1988** [lingarajsankaravelu/Katex#16]
Hi, i want to set my text in view on the left. How can i do this?

**Comment by Aiosa** [comment]
By using this feature you basically restrain youreslf from using such feature. So you need to go inside the implementation and redefine something - pribably the CSS style sheet. Unfortunately, this implementation does not allow much custom modifications. I already advised about some customization here in issues, so either look at that and try to figure out how to adjust the code, or try different implementation (at least one exsists)

**Comment by edward1988** [comment]
> By using this feature you basically restrain youreslf from using such feature. So you need to go inside the implementation and redefine something - pribably the CSS style sheet. Unfortunately, this implementation does not allow much custom modifications. I already advised about some customization here in issues, so either look at that and try to figure out how to adjust the code, or try different implementation (at least one exsists)

**Comment by edward1988** [comment]
Thanks for your reply
