### ISSUE TITLE
Katex fails to parse matrix expressions

### ISSUE THREAD

**Issue by Priyanshibrahmbhatt85** [lingarajsankaravelu/Katex#17]
webview showing $M = \\matrix{~ & x & y \\cr\n       
           A & 1 & 0 \\cr\n              
    B & 0 & 1 \\cr}$ instead of 
              x     y
M= A     1     0
       B     0     1

**Comment by lingarajsankaravelu** [comment]
@Priyanshibrahmbhatt85   I have tried rendering the above math expression in  [katex page](https://katex.org/), it was unable to render your latex data. can you confirm once

**Comment by Priyanshibrahmbhatt85** [comment]
this is the error i am getting :
"KaTeX auto-render: Failed to parse M = \matrix{~ & x & y \cr A & 1 & 0 \cr B & 0 & 1 \cr} with ", source: file:///android_asset/katex/contrib/auto-render.min.js

**Comment by lingarajsankaravelu** [comment]
@Priyanshibrahmbhatt85   please verify your latex expression first. 
<img width="320" alt="Screenshot 2019-03-22 at 12 49 36 PM" src="https://user-images.githubusercontent.com/8025146/54806796-283c5900-4ca1-11e9-880b-6e63cdbd6fc4.png">

**Comment by lingarajsankaravelu** [comment]
closing the thread
