### ISSUE TITLE
Math Expression rendering Issue using HTML

### ISSUE THREAD

**Issue by Ramachandran322** [lingarajsankaravelu/Katex#19]
Hello,

I am rendering math expression using the HTML content. The math expression is not rendering properly. I have verified the math xpression in https://katex.org/ and it's showing properly in this website.

However, when I use the expression with the html content, it's messed up. Here is the math expression,

x = \begin{cases}    a &\text{if } b \\    c &\text{if } d \end{cases}

Attached the screenshot on how it's rendering,
![mathview](https://user-images.githubusercontent.com/50147857/56975898-5e69d400-6b8f-11e9-8d1e-fb088b2ea9ee.jpg)

Below is the image for html content I have used:
![htmlmath](https://user-images.githubusercontent.com/50147857/56976420-860d6c00-6b90-11e9-93a7-f2ad1f2657e0.png)

 Here is the correct mathview rendered in http:katex.org/ 
![CorrectMAthView](https://user-images.githubusercontent.com/50147857/56976105-d3d5a480-6b8f-11e9-843b-01f50e55ad89.png)

Awaiting your response for this problem. I have to render the math expression only as HTML content. Please reply soon.

**Comment by lingarajsankaravelu** [comment]
Are you using this version  of the library 
'in.hourglass.mathrender:katexmathview:1.0' ?
If so use the code from modifications branch and make sure you wrap math formulas around $mathformula$ . It should work fine.

**Comment by Aiosa** [comment]
Well, i would double/triple check the special characters and the way they are parsed. You are not using the '&' character but the html equivalent ones, which are used to display them, not actually use them. Especially the `&amp;amp; `expression is a bit off. You're using `&amp;` character for the first letter of `&amp;` sequence

**Comment by lingarajsankaravelu** [comment]
@Ramachandran322  Did you try what we have suggested?

**Comment by Ramachandran322** [comment]
Hello,

Thanks for your fast response !!!

Yes, I'm using this version of your library code                                                                      
 'in.hourglass.mathrender:katexmathview:1.0' .

I have tried what you have said in a string resource as below,

<string name="single_formula">$\\int_0^\\infty e^{-x^2} dx=\\frac{\\sqrt{\\pi}}{2}$</string>

the same as the example you have given in the sample project. It `works` perfectly fine and rendering properly. But my requirement is only to render with HTML tags. Below is the HTML tag that I'm using. which you can check.

`<p><span class="note-math-description"><span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>x</mi><mo>=</mo><mrow><mo fence="true">{</mo><mtable><mtr><mtd><mstyle scriptlevel="0" displaystyle="false"><mi>a</mi></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="false"><mrow><mtext>if&nbsp;</mtext><mi>b</mi></mrow></mstyle></mtd></mtr><mtr><mtd><mstyle scriptlevel="0" displaystyle="false"><mi>c</mi></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="false"><mrow><mtext>if&nbsp;</mtext><mi>d</mi></mrow></mstyle></mtd></mtr></mtable></mrow></mrow><annotation encoding="application/x-tex">x = \begin{cases}    a &amp;amp;\text{if } b \\    c &amp;amp;\text{if } d \end{cases}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height: 0.43056em; vertical-align: 0em;"></span><span class="mord mathdefault">x</span><span class="mspace" style="margin-right: 0.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right: 0.277778em;"></span></span><span class="base"><span class="strut" style="height: 3.00003em; vertical-align: -1.25003em;"></span><span class="minner"><span class="mopen delimcenter" style="top: 0em;"><span class="delimsizing size4">{</span></span><span class="mord"><span class="mtable"><span class="col-align-l"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height: 1.69em;"><span class="" style="top: -3.69em;"><span class="pstrut" style="height: 3.008em;"></span><span class="mord"><span class="mord mathdefault">a</span></span></span><span class="" style="top: -2.25em;"><span class="pstrut" style="height: 3.008em;"></span><span class="mord"><span class="mord mathdefault">c</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height: 1.19em;"><span class=""></span></span></span></span></span><span class="arraycolsep" style="width: 1em;"></span><span class="col-align-l"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height: 1.69em;"><span class="" style="top: -3.69em;"><span class="pstrut" style="height: 3.008em;"></span><span class="mord"><span class="mord text"><span class="mord">if&nbsp;</span></span><span class="mord mathdefault">b</span></span></span><span class="" style="top: -2.25em;"><span class="pstrut" style="height: 3.008em;"></span><span class="mord"><span class="mord text"><span class="mord">if&nbsp;</span></span><span class="mord mathdefault">d</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height: 1.19em;"><span class=""></span></span></span></span></span></span></span><span class="mclose nulldelimiter"></span></span></span></span></span><span class="note-latex-description" style="display: none;">x = \begin{cases}    a &amp;\text{if } b \\    c &amp;\text{if } d \end{cases}</span></span><br></p>`

In the meanwhile, I will also try the answer given by Aiosa.

**Comment by Ramachandran322** [comment]
We are using a summer note plugin in the backend for getting the HTML tags for math expression, 
https://rawgit.com/tylerecouture/summernote-math/master/Example/example.html

**Comment by lingarajsankaravelu** [comment]
@Ramachandran322 

[https://github.com/lingarajsankaravelu/Katex/blob/d0e9618015b5c8372cb0bcce5e7e28ec400ca11e/katexmathview/src/main/assets/katex/contrib/auto-render.min.js#L126-L147](auto-render-min.js)

Refer to the highlighted lines  in the above file. Inorder to differentiate between normal text and a formula in a String Katex library looks for delimiters like $$,$, \\[, \\(. So if you want to render math, you must use any one of the delimiter and enable or disable other delimiters. The choice is up to you. 

My suggestion to you would be. All your tex are placed inside  application/x-tex tag. so before passing the data to the mathview parse the data using Jsoup and look for the above tag, if it exists add delimiter and handover the data to the mathview.

**Comment by Ramachandran322** [comment]
@lingarajsankaravelu 

Thank you. Could you please provide me with a complex math expression with the delimiters included. Like an integral or matrix or a sqrt function. It would be nice for us to take it as a reference and implement the same.

**Comment by lingarajsankaravelu** [comment]
With all due respect @Ramachandran322 , that is more like spoon feeding. you can find a integeral or matrix formula on your own through google.  - [sample project ](https://github.com/lingarajsankaravelu/KatexTuts)

Closing this thread.

**Comment by Ramachandran322** [comment]
@lingarajsankaravelu 

Well, this case is not yet closed. And I am not asking for spoon feeding. Even the sample html tag you have given on your page was not rendering properly. Below is the screenshot, 

![katex_sample](https://user-images.githubusercontent.com/50147857/57067596-182a8700-6ced-11e9-8ced-54eea1550f52.jpg)

This is the reason I am asking you to provide a better sample.

There was no proper documentation on how to use your library along with a contents. Failed to render properly with your sample. Your sample projects have integrated only with the Strings and not html.

**Comment by lingarajsankaravelu** [comment]
@Ramachandran322  
So the sample project that you use right won't render your  formula with text continously, its a different problem called displaying data in multiline. 
If you want to display it as a multiline(continously) like below

 if x:35::48:60, find the value of x , 


use the code from modification branch, it supports multiline display. 
About the html part. I work in  edtech space where our android app displays text and formula together from  html data, which is rendering fine. If you are not taking my word for it or your requirement is something else, feel free to read the documentation in katex.org and make necessary changes in  this repo, so that all of us can benefit from it.
