### ISSUE TITLE
Patches on WebView

### ISSUE THREAD

**Issue by shazrazdan** [lingarajsankaravelu/Katex#20]
Not all of my MathView texts contain Latex (most do). This is the screenshot of one passage which does not have any Latex tags and it is being rendered like this. What could a possible fix be?
![image](https://user-images.githubusercontent.com/19644577/56986725-4ae34c80-6b40-11e9-9d3a-3986ce932976.png)

**Comment by lingarajsankaravelu** [comment]
Does your text contain any html tags, can you share us the content that you are trying to display?

**Comment by shazrazdan** [comment]
Thanks for replying. This is the string I tried to render. It is stored in the device locally. Also, the issue is not present in all devices. Only a handful of devices. 

```
<p>
    As Xenophanes recognized as long ago as the sixth century before Christ,
    whether or not God made man in His own image, it is certain that man makes
    gods in his. The gods of Greek mythology first appear in the writings of
    Homer and Hesiod, and, from the character and actions of these picturesque
    and, for the most part, friendly beings, we get some idea of the men who
    made them and brought them to Greece.
</p>
<p>
    But ritual is more fundamental than mythology, and the study of Greek
    ritual during recent years has shown that, beneath the belief or skepticism
    with which the Olympians were regarded, lay an older magic, with
    traditional rites for the promotion of fertility by the celebration of the
    annual cycle of life and death, and the propitiation of unfriendly ghosts,
    gods or demons. Against this dark and dangerous background arose Olympic
    mythology on the one hand and early philosophy and science on the other.
</p>
<p>
    In classical times the need of a creed higher than the Olympian was felt,
    and Aeschylus, Sophocles and Plato finally evolved from the pleasant but
    crude polytheism the idea of a single, supreme and righteous Zeus. But the
    decay of Olympus led to a revival of old and the invasion of new magic
    cults among the people, while some philosophers were looking to a vision of
    the uniformity of nature under divine and universal law.
</p>
<p>
    From Sir William Cecil Dampier, <em>A Shorter History of Science</em>,
    ©1957, Meridian Books.
</p>
```

**Comment by lingarajsankaravelu** [comment]
@shazrazdan 
I have tried the same with the katex release version 1.0 and  updated version of the katex code in modification branch. It displays like fine. No clue on why its displaying content in an odd way for you.
can you share us how your layout design is and the way you set data in the mathview? 

![Screenshot_1556861202](https://user-images.githubusercontent.com/8025146/57121254-e15b7c00-6d93-11e9-94f5-f3ecaa829c61.png)![Screenshot_1556861231](https://user-images.githubusercontent.com/8025146/57121255-e1f41280-6d93-11e9-87c1-99b14be86b78.png)

**Comment by lingarajsankaravelu** [comment]
@shazrazdan  any updates with this particular issue?
