### ISSUE TITLE
Need to know how to make the Katex inline

### ISSUE THREAD

**Issue by imarindam** [lingarajsankaravelu/Katex#22]
Hello developer,
First of all thanks a lot for developing this for Android. My app has lot of katex code which is fetched from server. This app helps me to show them quickly without depending on the server to decode and convert it to image.
I have a request though, can I show the katex equations and notations inline while the string is in $.....$ format?
Please let me know how to do that. Thanks again.

**Comment by lingarajsankaravelu** [comment]
@imarindam Yes you can. I think you are using 
`compile 'in.hourglass.mathrender:katexmathview:1.0` in your project which does not allow you to display text and formula inline. Please use the code from modification branch, that will render the content as expected. I will push a  release with recent changes, sometimes this week.

**Comment by imarindam** [comment]
Thank you so much for the info.
Glad to hear that the update will come soon.

**Comment by lingarajsankaravelu** [comment]
implementation 'in.hourglass.mathrender:katexmathview:1.0.1'
