### ISSUE TITLE
Vertical/Horizontal Scrolling, Zoom etc not working

### ISSUE THREAD

**Issue by imarindam** [lingarajsankaravelu/Katex#23]
Hello, 
This development is really helpful and its awesome so far.
But it needs some horizontal,vertical scrolling and zooming control as webviews.
My settings: `mathView.setClickable(false);`
I tried: 
`mathView.getSettings().setSupportZoom(true);
mathView.getSettings().setBuiltInZoomControls(true);
mathView.setHorizontalScrollBarEnabled(true);
mathView.setVerticalScrollBarEnabled(true);`

None of them seems working.
However if I add MathView as achild of Nested Scrolling view only vertical scrolling work. But I need webview like scrolling and zooming support.
If you can help me I will be highly obliged.
Thank you.

**Comment by lingarajsankaravelu** [comment]
@imarindam is this a problem with the recent release version 1.0.1?

**Comment by imarindam** [comment]
@lingarajsankaravelu Actually, I have not tried the scrolling and zooming part with the previous release, as it was not needed as the length of the codes I was fetching was small.
With the latest release I was working with many codes and HTML so I faced this.

**Comment by lingarajsankaravelu** [comment]
ok @imarindam let me check, can you share me a data which requires the mentioned features.

**Comment by imarindam** [comment]
@lingarajsankaravelu Sure.
There are many HTML Texts.
Below is one of it which contains Tables, Equations.

`<p>(a) $\frac{1}{18}$</p> <p>(b) $\frac{7}{18}$</p> <p>(c) $\frac{5}{18}$</p> <p>(d) $\frac{1}{9}$</p> <p><!--more--></p> <p><strong>Ans: $\frac{5}{18}$</strong></p> <p><strong>Solution</strong></p> <p>Hints : &#8211; Let, C be the event that &#8216;the difference of nos. shown is 1&#8217;</p> <p>$C = \left \{ \left ( 1, 2 \right )\left ( 2, 1 \right )\left ( 2, 3 \right )\left ( 3, 2 \right )\left ( 3, 4 \right )\left ( 4, 3 \right )\left ( 4, 5 \right )\left ( 5, 4 \right )\left ( 5, 6 \right )\left ( 6, 5 \right ) \right \}$</p> <p>∴  $n\left ( C \right ) = 10$ ,      $n\left ( S \right ) = 36$</p> <p>∴  $P\left ( C \right ) = \frac{n\left ( C \right )}{n\left ( S \right )}$</p> <p>$=\frac{10}{36}$</p> <p>$=\frac{5}{18}$</p> <p><strong>Table Example:</strong></p> <table border="1" style="border-collapse: collapse; width: 596px;"> <tbody> <tr> <td style="width: 101px; text-align: center;">$2x+y^{2}$</td> <td style="width: 127px; text-align: center;">$C = \left \{ \left ( 1, 2 \right )\left ( 2, 1 \right )\left ( 2, 3 \right )\left ( 3, 2 \right )\left ( 3, 4 \right )\left ( 4, 3 \right )\left ( 4, 5 \right )\left ( 5, 4 \right )\left ( 5, 6 \right )\left ( 6, 5 \right ) \right \}$</td> <td style="width: 168px; text-align: center;">$\large \frac{12-n+5}{30\left ( n-5 \right )}=\frac{1}{\left ( n-4 \right )\left ( n-5 \right )}$</td> <td style="width: 131px; text-align: center;">$\large \frac{2}{5\left ( n-5 \right )}=\frac{1}{\left ( n-4 \right )\left ( n-5 \right )}+\frac{1}{30}$</td> </tr> <tr> <td style="width: 101px; text-align: center;">Row 2 Column 1</td> <td style="width: 127px; text-align: center;">Row 2 Column 2</td> <td style="width: 168px; text-align: center;">Row 2 Column 3</td> <td style="width: 131px; text-align: center;">Row 2 Column 4</td> </tr> <tr> <td style="width: 101px; text-align: center;">Test</td> <td style="width: 127px; text-align: center;">Test</td> <td style="width: 168px; text-align: center;">$\frac{5}{18}$</td> <td style="width: 131px; text-align: center;"></td> </tr> </tbody> </table>`

**Comment by lingarajsankaravelu** [comment]
@imarindam that was a bug. thanks for reporting, i was able to fix it and do a test as well. I will be pushing a release as version 1.0.2 within an hour. Please watch out.

**Comment by lingarajsankaravelu** [comment]
@imarindam  use 

```implementation 'in.hourglass.mathrender:katexmathview:1.0.2'```
