### ISSUE TITLE
How to resolve this issue a security alert by Google after using Mathview inside my app. They are saying i am using Vulnerable Javascript Libs. assets/jquery.min.js

### ISSUE THREAD

**Issue by iamAliRaza** [lingarajsankaravelu/Katex#32]
![screenshot](https://user-images.githubusercontent.com/22626350/66541639-03c2a400-eb41-11e9-89bc-c02634be6e19.png)

**Comment by Aiosa** [comment]
Hello, this is definitely something the library should update. It may be that the jquery library used is deprecated or has known issues, so as temporary fix I advice to replace the jquery with newer version, just download google's one that should be fine and replace the current one in assets folder. Also, remake it the same so the src link will find it. Unfortunately, it may take a while for the developer to update.

PS i noticed late that he already self-assigned it so maybe it will be fixed soon..

**Comment by lingarajsankaravelu** [comment]
This was fixed by @BrunoRCE and the changes were merged  with master branch . Use the branch for now. This will be available with 1.0.3 release

**Comment by eorhan** [comment]
I installed jquery 3.4.1 but it overwrites again

**Comment by lingarajsankaravelu** [comment]
@eorhan . I have no idea, how or where did you install jquery 3.4.1. I have two apps for my current organisation on play store, which uses the changes from @BrunoRCE  and I can say with 100% confident that the vulnerability was fixed. pull the master branch and use the code as module in your project instead.

**Comment by omzesha** [comment]
Any update on the release date of 1.0.3?

**Comment by lingarajsankaravelu** [comment]
@omzesha ll put it up tmrw.

**Comment by omzesha** [comment]
Thank you so much sir!
Will be waiting.

**Comment by omzesha** [comment]
@lingarajsankaravelu waiting

**Comment by lingarajsankaravelu** [comment]
@omzesha published 1.0.3 . Thanks for the reminder.
