### ISSUE TITLE
Security Alert Issue in Play Store

### ISSUE THREAD

**Issue by gladwinbobby** [lingarajsankaravelu/Katex#37]
I'm getting the following error notice in the play store after publishing the APK.

![WhatsApp Image 2020-02-21 at 6 05 30 PM](https://user-images.githubusercontent.com/18662591/75035123-c6015f00-54d4-11ea-84e1-ffe08e65ed6f.jpeg)

**Comment by Aiosa** [comment]
Please check other issues before creating a new one https://github.com/lingarajsankaravelu/Katex/issues/32

**Comment by Aiosa** [comment]
Please check the other issues before creatinga new one https://github.com/lingarajsankaravelu/Katex/issues/32
