### ISSUE TITLE
Horizontal Scrolling??!!

### ISSUE THREAD

**Issue by manassharma07** [lingarajsankaravelu/Katex#4]
When equations are too big and go out of bounds then how do I enable horizontal scrolling?

**Comment by lingarajsankaravelu** [comment]
@manassharma07  Horizontal scrolling was  not implemented with the current release. Thank you for pointing it out. Will add it with the next release.

**Comment by manassharma07** [comment]
Hi there @lingarajsankaravelu 
Just checking in to see if there is any progress in resolving the issue?
Thanks

**Comment by lingarajsankaravelu** [comment]
@manassharma07 I have not wrote the fix yet. Caught up with work. Really sorry about. Will release with the fix in next two weeks.

**Comment by lingarajsankaravelu** [comment]
Horizontal or vertical scrolling wont be necessary as the current changes allows the text display to be handled inline. so whatever rendered on webview will be line by line, So horizontal and vertical lines won't be necessary.
