### ISSUE TITLE
how can i set coustom font in katex view 

### ISSUE THREAD

**Issue by mehulTank** [lingarajsankaravelu/Katex#40]
I am using this library in my application I need to use another font so can I use that other font?
if can I customize font then let me know any document or some method for that.

Thanks & Regards 
Mehul Tank

**Comment by Aiosa** [comment]
katex is web-based, so css should do the trick. try using something like `.katex { font-size: 1em !important; }` (https://stackoverflow.com/questions/50896041/katex-font-size) but set there your desired font instead. also make sure the font is recognized, e.g. either use a supported one, or include the font file in HTML header

**Comment by mehulTank** [comment]
@Aiosa  Thanks for your replay yes I will do that I had seen margin but I want to use Helvetica font instead of   katex_caligrafy or catex_ams cam I use Helvetica?

**Comment by Aiosa** [comment]
Check it here, to be honest I don't know much about custom fonts for katex as I've never needed it.. https://katex.org/docs/font.html though it gives only general info... 

I suggest you to try reverse engineering (https://stackoverflow.com/questions/37256331/is-it-possible-to-open-developer-tools-console-in-chrome-on-android-phone) to see the structure of the rendered result to understand it and possibly play with the css attributes to see what's working...

**Comment by lingarajsankaravelu** [comment]
@mehulTank I have tried using Custom fonts for Katex rendering long back, It never worked or ended up not rendering most of the formulas. So all the best.

**Comment by mehulTank** [comment]
I am using katex library but I am getting different font styles.

![app screen shot](https://user-images.githubusercontent.com/15247268/86273570-1c527d00-bbee-11ea-895e-11d2aef16762.PNG)
in Render Katex view HCI is Different font in question and different font in the option.

![response](https://user-images.githubusercontent.com/15247268/86273977-a00c6980-bbee-11ea-81b4-c85e427710d3.PNG)


here I have the response in question HCI is normal Text while some of option HCI text with encoded with maths function so how can I display font same everywhere if maths function or simple string data. why it is different getting?
