### ISSUE TITLE
<img /> tag not working

### ISSUE THREAD

**Issue by chiragmittal19** [lingarajsankaravelu/Katex#42]
I'm trying to show an image in `MathView`, but it is not getting rendered.

Content passed in `setDisplayText()` method -

```
<img src="http://some/publicly/available/image.png" />
```

Version - 1.0.3

**Comment by lingarajsankaravelu** [comment]
@chiragmittal19 This has nothing to do with the library. Please refer this https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6
