### ISSUE TITLE
Disable Zoomin controls

### ISSUE THREAD

**Issue by sempsmahad** [lingarajsankaravelu/Katex#47]
### Description
- Is there a way to disable these zoom in controls that usually appear on web views, they are kind of irritating
![Screenshot_20220414_171032_com KH69 passmath debug](https://user-images.githubusercontent.com/26974575/163409071-d3a4cff5-851f-4ad0-a23e-c04fd1fd9873.jpg)

**Comment by Aiosa** [comment]
The element the  math is rendered into is just an ordinary WebView. Look into the WebView android API and you will find methods that will remove it for you. Search engines are powerful. https://stackoverflow.com/questions/10766669/how-to-remove-zoom-buttons-on-android-webview

Use the Google, Luke!

**Comment by sempsmahad** [comment]
Thank you, Obi-Wan I forget myself.

That did the job, [this answer](https://stackoverflow.com/a/10766678/8872691) to be specific 
![obi-wan-kenobi-force](https://user-images.githubusercontent.com/26974575/163550113-282718d5-25ba-420a-adf2-8dc82775efdb.gif)
