### ISSUE TITLE
Font Size issue in android

### ISSUE THREAD

**Issue by shanuvshaji** [lingarajsankaravelu/Katex#5]
Error Log:

E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/themes/style.css

**Comment by lingarajsankaravelu** [comment]
@shanuvshaji  I appreciate the time you put in to inform me about the bug. Will fix it in the upcoming release.

**Comment by shanuvshaji** [comment]
Can you please help me,
Some text is not rendering in my app, can you tell me what is the issue?

Eg:
"Assertion (A): If <math  xmlns="http://www.w3.org/1998/Math/MathML"><mrow><mo stretchy="false">∫</mo><mrow><mfrac><mrow><mn>1</mn></mrow><mrow><mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo></mrow></mfrac><mi>d</mi><mi>x</mi></mrow></mrow><mo>=</mo><msup><mrow><mrow><mrow><mi mathvariant="normal">ln</mi></mrow><mo>⁡</mo><mrow><mfenced separators="|"><mrow><mi>f</mi><mfenced separators="|"><mrow><mi>x</mi></mrow></mfenced></mrow></mfenced></mrow></mrow></mrow><mrow><mn>2</mn></mrow></msup><mo>+</mo><mi>c</mi><mi mathvariant="normal"> </mi><mi mathvariant="normal">t</mi><mi mathvariant="normal">h</mi><mi mathvariant="normal">e</mi><mi mathvariant="normal">n</mi><mi mathvariant="normal"> </mi><mi>f</mi><mfenced separators="|"><mrow><mi>x</mi></mrow></mfenced><mo>=</mo><mfrac><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mfrac><mi>x</mi><mo>.</mo></math><br>Reason (R): When <math  xmlns="http://www.w3.org/1998/Math/MathML"><mi>f</mi><mfenced separators="|"><mrow><mi>x</mi></mrow></mfenced><mo>=</mo><mfrac><mrow><mi>x</mi></mrow><mrow><mn>2</mn></mrow></mfrac><mo>,</mo><mrow><mo stretchy="false">∫</mo><mrow><mfrac><mrow><mn>1</mn></mrow><mrow><mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo></mrow></mfrac><mi>d</mi><mi>x</mi></mrow></mrow><mo>=</mo><mrow><mo stretchy="false">∫</mo><mrow><mfrac><mrow><mn>2</mn></mrow><mrow><mi>x</mi></mrow></mfrac><mi>d</mi><mi>x</mi></mrow></mrow><mo>=</mo><mn>2</mn><mrow><mrow><mi mathvariant="italic">ln</mi></mrow><mo>⁡</mo><mrow><mfenced open="|" close="|" separators="|"><mrow><mi>x</mi></mrow></mfenced></mrow></mrow><mo>+</mo><mi>c</mi></math><br>"
