### ISSUE TITLE
is it supported in react-native also?

### ISSUE THREAD

**Issue by gmchaturvedi1** [lingarajsankaravelu/Katex#6]
i am using react-native .can i use this .Kindly guide me if yes how can i can setup this.

**Comment by lingarajsankaravelu** [comment]
@gmchaturvedi1 Really sorry to get back to you on this after a long time. caught with my work. There is a plan to release it for react-native it as well. I have to wrap the current library. Will release in the upcoming version .

**Comment by GaudamThiyagarajan** [comment]
has this enhancement been pushed.

**Comment by eranilsharma** [comment]
Is I set a single line and multiline my webview on the click on it?
