### ISSUE TITLE
Pinch to zoom and scroll not working for MathView

### ISSUE THREAD

**Issue by anirudha-banerjee** [lingarajsankaravelu/Katex#7]
I am using your mathview to display long content with formula. The content gets displayed correctly, but i am not being able to scroll the webview. I've tried adding the view at rumtime and also by xml, but scrolling and pinch and zoom is not working.

`mWebView.setClickable(false);  
        mWebView.setTextSize(16);
        mWebView.setTextColor(ContextCompat.getColor(getApplicationContext(),android.R.color.black));        mWebView.setViewBackgroundColor(ContextCompat.getColor(getApplicationContext(),android.R.color.white));
        mWebView.getSettings().setLoadsImagesAutomatically(true);
        mWebView.setVerticalScrollBarEnabled(true);
        mWebView.getSettings().setSupportZoom(true);
        mWebView.getSettings().setBuiltInZoomControls(true);
        parentLayout.addView(mWebView);`

I have also tried these attributes through xml, but scroll and zoom dosen't work.
Pls can you tell me whether it's an issue in your library or a problem in my implementation.

Also, i have checked your library code, and it shows, while calling the MathView constructor the below function gets called. But these attributes can also be overwritten when i explicitly call them, like what i did in the above code, right?
`private void configurationSettingWebView()
     {
         getSettings().setJavaScriptEnabled(true);
         getSettings().setAllowFileAccess(true);
         getSettings().setDisplayZoomControls(false);
         getSettings().setBuiltInZoomControls(false);
        getSettings().setSupportZoom(false);
        getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);
      }`

Please can you help me a bit, as to where i'm going wrong?

**Comment by lingarajsankaravelu** [comment]
hey @anirudha-banerjee  am pretty sure it is a problem with library. Can you please share the content you tried to display with the library. So that I can test it and update on the same.

**Comment by anirudha-banerjee** [comment]
hello,
I have given a sample content below.
`<p style="text-align:justify"><span style="font-size:18px"><span style="color:#4e5f70"><span style="font-family:Helvetica"><strong>Complex Number and Its Representation</strong></span></span>
    </span>
</p>

<p style="text-align:justify">
    <br />
    <span style="color:#4e5f70"><span style="font-family:Helvetica">A number in the form of z = x + iy, where x , y<span class="math-tex">\(\in\)</span>R, i = <span class="math-tex">\(\sqrt{-1}\)</span> is called a complex number. The real numbers x and y are respectively called
    <br /> real and imaginary parts of complex number z.
    <br /> i.e. x = Re(z) and y = Im(z)
    <br />
    <br /> The complex number z = x + iy is represented by a point P, whose coordinates are referred to rectangular axes XOX&cent; and YOY &cent; which
    <br /> are called real and imaginary axes, respectively.
    <br /> This plane is called argand plane or Gaussian plane. The magnitude of the complex number z is |z| =&nbsp;<span class="math-tex">\(\sqrt{x^2+y^2}\)</span> and <span class="math-tex">\(\theta\)</span>= tan<span class="math-tex">\(^1\)</span><span class="math-tex">\((\frac{y}{x})\)</span>
    <br />
    <br /> A complex number z is said to be purely real or imaginary, if y = 0 or x = 0, respectively.</span>
    <br />
    <br />
    <img alt="" height="168" src="Images/c.png" width="210" />
    </span>
</p>

<p style="text-align:justify">
    <br />
    <span style="color:#4e5f70"><span style="font-family:Helvetica"><strong>NOTE</strong>&nbsp;<em> Iota (i) is neither 0 nor greater than 0 nor less than 0.</em></span></span>
</p>

<p style="text-align:justify">
    <br />
    <span style="color:#4e5f70"><span style="font-family:Helvetica"><strong>Integral Powers of <em>i</em></strong><em>&nbsp; </em>We know that, i = <span class="math-tex">\(\sqrt{-1}\)</span>,<em> i<span class="math-tex">\(^2\)</span></em> = - 1,&nbsp;<span class="math-tex">\(i^3\)</span> = -i ,&nbsp;<span class="math-tex">\(i^4\)</span> = -1, etc.
    <br /> In general, i<span class="math-tex">\(^{4n}\)</span> = 1,<span class="math-tex">\(i^{ 4n + 1}\)</span> =i , <span class="math-tex">\(i^{4n + 2}\)</span> = -1, <span class="math-tex">\(i^{4n + 3}\)</span> = -1 ,<span class="math-tex">\(\forall\)</span> any integer n.
    <br /> The sum of four consecutive powers of i is zero. i.e. <span class="math-tex">\(i^n+i ^{n+1}+i^{n+2}+i^{n+3}=0 \)</span>&nbsp; <span class="math-tex">\( n\in1 \)</span></span>
    </span>
</p>

<p style="text-align:justify">
    <br />
    <span style="color:#4e5f70"><span style="font-family:Helvetica"><span style="font-size:16px"><strong>Algebra of Complex Numbers</strong></span></span>
    </span>
</p>

<p style="text-align:justify">
    <br />
    <span style="color:#4e5f70"><span style="font-family:Helvetica"><em>If z<span class="math-tex">\(_1\)</span> = x<span class="math-tex">\(_1\)</span> + iy<span class="math-tex">\(_1\)</span> and z<span class="math-tex">\(_2\)</span> = x<span class="math-tex">\(_2\)</span> + iy<span class="math-tex">\(_2\)</span> are two complex numbers, then</em>
    <br />
    <br /> (i) Addition of complex numbers is z<span class="math-tex">\(_1\)</span> + z<span class="math-tex">\(_2\)</span> = (x<span class="math-tex">\(_1\)</span> + x<span class="math-tex">\(_2\)</span> ) + i( y<span class="math-tex">\(_1\)</span> + y<span class="math-tex">\(_2\)</span> )
    <br /> Its additive identity is 0 + 0i.
    <br /> (ii) Subtraction of complex numbers is z<span class="math-tex">\(_1\)</span> - z<span class="math-tex">\(_2\)</span> = (x<span class="math-tex">\(_1\)</span> - x<span class="math-tex">\(_2\)</span> ) + i( y<span class="math-tex">\(_1\)</span> - y<span class="math-tex">\(_2\)</span> )
    <br /> (iii) Multiplication of complex numbers is z<span class="math-tex">\(_1\)</span>z<span class="math-tex">\(_2\)</span> = (x<span class="math-tex">\(_1\)</span>x<span class="math-tex">\(_2\)</span> - y<span class="math-tex">\(_1\)</span> y<span class="math-tex">\(_2\)</span> ) + i(x<span class="math-tex">\(_1\)</span> y<span class="math-tex">\(_2\)</span> + x<span class="math-tex">\(_2\)</span> y<span class="math-tex">\(_1\)</span>

`

The latex conversion is not a problem, the problem is scroll and pinch to zoom and other basic webview functionalities.
I have also attached the html for the above content. Please rename the file to .html

[sample_mathview_content.html.docx](https://github.com/lingarajsankaravelu/Katex/files/1203209/sample_mathview_content.html.docx)

**Comment by anirudha-banerjee** [comment]
hello,
I have solved the issue by overwriting your lib.
Following are the changes i did:
*>Comment out onTouchEvent in your MathView.java
*>Change configurationSettingWebView() values to true, also added setVerticalScrollBarEnabled(true);
        setHorizontalScrollBarEnabled(true);
*>In your katex.css file, removed overflow: hidden in .katex .katex-mathml {}
After these changes MathView works as a normal webview with Latex rendering intact.
Now i'm being able to scroll horizontal as well as vertical. Also, the clicks are happening and zoom is also happening.

**Comment by lingarajsankaravelu** [comment]
Interesting . Will check and get back to you.

**Comment by lingarajsankaravelu** [comment]
Suggested changes upated to modification branch, will be push in release version 1.0.1
