### ISSUE TITLE
Are all the fonts required for rendering? 

### ISSUE THREAD

**Issue by ArsalaBangash** [lingarajsankaravelu/Katex#8]
The Katex fonts assets folder currently takes up 1.5mb of my apk. Are all the fonts necessary or can some be removed?

**Comment by lingarajsankaravelu** [comment]
@ArsalaBangash  Yes its necessary. These fonts are used by katex by default. Never tried removing few and checked.

**Comment by mwshubham** [comment]
Can we try this and see the impact not sure if each font is required for Android.
